name: Sync Latest Code to Windows Server

on:
  push:
    branches:
      - staging

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (latest LTS)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (with npm ci)
        run: |
          if [ ! -d "node_modules" ]; then
            echo "Instalando dependencias con npm ci..."
            npm ci  # Utiliza npm ci para instalaciones más rápidas en CI
          else
            echo "Las dependencias ya están instaladas, usando caché."
          fi

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 -H 107.178.98.246 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Update Windows Server with GitHub Code
        run: |
          # Conexión SSH directa con clave privada
          ssh -T -o StrictHostKeyChecking=no -p 22 administrator@107.178.98.246 << 'EOF'
            cd C:\Cistem\dev\task-app
            git pull https://MoisesNevCistem:${{ secrets.ACC_TOKEN }}@github.com/MoisesNevCistem/task-app.git staging --allow-unrelated-histories
          EOF

      - name: Final message
        run: echo "Pull realizado en el servidor Windows con éxito"
