name: Sync Latest Code to Windows Server

on:
  push:
    branches:
      - staging

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (latest LTS)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (with npm ci)
        run: npm ci

      - name: Set up SSH
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 -H 107.178.98.246 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Update Windows Server with GitHub Code
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PWD_USER }}
          ACCESS_TOKEN: ${{ secrets.ACC_TOKEN }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -T -o StrictHostKeyChecking=no -p 22 administrator@107.178.98.246 << 'EOF'
            cd C:\Cistem\dev\task-app
            git pull --rebase https://MoisesNevCistem:${ACCESS_TOKEN}@github.com/MoisesNevCistem/task-app.git staging
          EOF

      - name: Final message
        run: echo "Pull realizado en el servidor Windows con éxito"
