# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Deploy to Windows

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Windows Host to Known Hosts
        run: |
          ssh-keyscan -H 107.178.98.246 >> ~/.ssh/known_hosts

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Windows
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PWD_USER }} # Carga la contraseña desde los secretos
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=keyboard-interactive,password -p 22 administrator@107.178.98.246 << 'EOF'
            powershell.exe -Command " 
              # Cambiar directorio de la aplicación
              Set-Location -Path 'C:\Cistem\dev\task-app'; 

              # Verificar si estamos en el repositorio de Git
              if (!(Test-Path .git)) {
                Write-Host 'Error: no es un repositorio de Git'; exit 1;
              }

              # Actualizar la aplicación
              git pull origin staging || { Write-Host 'Error al hacer git pull'; exit 1; }

              # Instalar dependencias
              npm install || { Write-Host 'Error al instalar dependencias'; exit 1; }

              # Reiniciar o iniciar el servidor
              pm2 restart task-app || pm2 start npm --name 'task-app' -- run dev || { Write-Host 'Error al iniciar el servidor'; exit 1; }

              Write-Host 'Despliegue completado exitosamente';
            "
          EOF
