# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Sync Latest Code to Windows Server

on:
  push:
    branches:
      - staging

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Si no necesitas Node.js, puedes eliminar este paso
      # - name: Set up Node.js (latest LTS)
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20'

      # Instalar sshpass solo si no está instalado, pero caché no es necesario
      - name: Install sshpass
        run: |
          if ! command -v sshpass &> /dev/null; then
            echo "sshpass not found, installing..."
            sudo apt-get update -qq && sudo apt-get install -y sshpass
          fi

      # Configuración de SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Añadir la clave del servidor al archivo known_hosts
          ssh-keyscan -p 22 -H 107.178.98.246 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Actualizar servidor Windows con el código de GitHub
      - name: Update Windows Server with GitHub Code
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PWD_USER }}
          ACCESS_TOKEN: ${{ secrets.ACC_TOKEN }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 22 administrator@107.178.98.246 << 'EOF'
            cd C:\Cistem\dev\task-app
            git pull https://MoisesNevCistem:${ACCESS_TOKEN}@github.com/MoisesNevCistem/task-app.git staging --allow-unrelated-histories
          EOF

      # Mensaje final
      - name: Final message
        run: echo "Pull realizado en MV :D"