# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Deploy to Windows

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Windows
        run: |
          ssh -v -p 22 desarrollo\cistem@192.168.0.130 << 'EOF'
            cd /z/Documents/example/task-app &&
            git pull origin staging &&
            npm install &&
            npm run dev &&
            pm2 restart task-app
          EOF
