# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Deploy to Windows

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Windows Host to Known Hosts
        run: |
          ssh-keyscan -p 22 -H 107.178.98.246 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts  # Verifica que el host ha sido agregado correctamente
          chmod 644 ~/.ssh/known_hosts  # Asegura que los permisos son correctos

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            !~/.npmrc
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Windows
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PWD_USER }}
          ACCESS_TOKEN: ${{ secrets.ACC_TOKEN }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 22 administrator@107.178.98.246 << 'EOF'
            cd C:\Cistem\dev\task-app
            git pull https://MoisesNevCistem:${ACCESS_TOKEN}@github.com/MoisesNevCistem/task-app.git staging
          EOF

      - name: Final message
        run: echo "Despliegue completado en el servidor Windows"
