# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Deploy to Windows

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Windows Host to Known Hosts
        run: |
          ssh-keyscan -H 107.178.98.246 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts  # Asegurarse de que tenga permisos correctos

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Windows
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PWD_USER }} # Carga la contraseña desde los secretos
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 22 administrator@107.178.98.246 << 'EOF'
            cd C:\Cistem\dev\task-app
            git pull origin staging
            npm install
            npm run dev
            echo "Despliegue completado exitosamente"
          EOF
