# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Deploy to Windows

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Windows Host to Known Hosts
        run: |
          ssh-keyscan -H 107.178.98.246 >> ~/.ssh/known_hosts

      - name: Deploy to Windows
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 Administrator@107.178.98.246 << 'EOF'
            # Cambiar directorio de la aplicación
            cd /c/Cistem/dev/task-app

            # Asegurarse de que git está en el PATH (necesario en Windows)
            if ! git --version > /dev/null 2>&1; then
              echo "Git no está en el PATH, añadiendo temporalmente"
              export PATH=$PATH:/c/Program\ Files/Git/bin
            fi

            # Actualizar la aplicación
            git pull origin staging

            # Instalar dependencias
            npm install

            # Ejecutar el servidor en modo desarrollo o reiniciar con pm2
            pm2 restart task-app || pm2 start npm --name "task-app" -- run dev
          EOF