# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Deploy to Windows

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Windows
        run: |
          ssh -p 22 "Desarrollo Cistem@192.168.0.130" "cd /z/Documents/example/task-app && git pull origin staging && pm2 restart task-app"
